"""user and library_member

Revision ID: 1dee96f8288a
Revises: 
Create Date: 2024-01-30 02:47:41.406799

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dee96f8288a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_information', sa.String(), nullable=True),
    sa.Column('membership_status', sa.Enum('ACTIVE', 'BLOCKED', name='membershipstatus'), nullable=True),
    sa.Column('membership_period', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('library_member_pkey'))
    )
    op.create_index(op.f('library_member_id_idx'), 'library_member', ['id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('library_member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['library_member_id'], ['library_member.id'], name=op.f('user_library_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('user_email_idx'), 'user', ['email'], unique=True)
    op.create_index(op.f('user_id_idx'), 'user', ['id'], unique=False)
    op.create_index(op.f('user_username_idx'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_username_idx'), table_name='user')
    op.drop_index(op.f('user_id_idx'), table_name='user')
    op.drop_index(op.f('user_email_idx'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('library_member_id_idx'), table_name='library_member')
    op.drop_table('library_member')
    # ### end Alembic commands ###
